In [255]:
def dy_dx(x):
  return 2*x

In [256]:
dy_dx(3)

6

In [257]:
import torch

In [258]:
x = torch.tensor(3.0, requires_grad=True)

In [259]:
y = x**2

In [260]:
x

tensor(3., requires_grad=True)

In [261]:
y

tensor(9., grad_fn=<PowBackward0>)

In [262]:
y.backward()

In [263]:
x.grad

tensor(6.)

In [264]:
import math

def dz_dx(x):
    return 2 * x * math.cos(x**2)

In [265]:
dz_dx(4)

-7.661275842587077

In [266]:
x = torch.tensor(4.0, requires_grad=True)

In [267]:
y = x ** 2

In [268]:
z = torch.sin(y)

In [269]:
x

tensor(4., requires_grad=True)

In [270]:
y

tensor(16., grad_fn=<PowBackward0>)

In [271]:
z

tensor(-0.2879, grad_fn=<SinBackward0>)

In [272]:
z.backward()

In [273]:
x.grad

tensor(-7.6613)

In [274]:
y.grad

/tmp/ipython-input-486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  y.grad


In [275]:
import torch

# Inputs
x = torch.tensor(6.7)  # Input feature
y = torch.tensor(0.0)  # True label (binary)

w = torch.tensor(1.0)  # Weight
b = torch.tensor(0.0)  # Bias

In [276]:
# Binary Cross-Entropy Loss for scalar
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8  # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

In [277]:
# Forward pass
z = w * x + b  # Weighted sum (linear part)
y_pred = torch.sigmoid(z)  # Predicted probability

# Compute binary cross-entropy loss
loss = binary_cross_entropy_loss(y_pred, y)

In [278]:
loss

tensor(6.7012)

In [279]:
# Derivatives:
# 1. dL/d(y_pred): Loss with respect to the prediction (y_pred)
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))

# 2. dy_pred/dz: Prediction (y_pred) with respect to z (sigmoid derivative)
dy_pred_dz = y_pred * (1 - y_pred)

# 3. dz/dw and dz/db: z with respect to w and b
dz_dw = x  # dz/dw = x
dz_db = 1  # dz/db = 1 (bias contributes directly to z)

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [280]:
print(f"Manual Gradient of loss w.r.t weight (dw): {dL_dw}")
print(f"Manual Gradient of loss w.r.t bias (db): {dL_db}")

Manual Gradient of loss w.r.t weight (dw): 6.691762447357178
Manual Gradient of loss w.r.t bias (db): 0.998770534992218


# **MENTOS SOLUTION**

In [281]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [282]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [283]:
w

tensor(1., requires_grad=True)

In [284]:
b

tensor(0., requires_grad=True)

In [285]:
z = w*x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [286]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [287]:
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [288]:
loss.backward()

In [289]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


In [290]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

In [291]:
x

tensor([1., 2., 3.], requires_grad=True)

In [292]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [293]:
y.backward()

In [294]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [295]:
# clearing grad
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [296]:
y = x ** 2
y

tensor(4., grad_fn=<PowBackward0>)

In [297]:
y.backward()

In [298]:
x.grad

tensor(4.)

In [299]:
x.grad.zero_()

tensor(0.)

In [300]:
# disable gradient tracking
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [301]:
y = x ** 2
y

tensor(4., grad_fn=<PowBackward0>)

In [302]:
y.backward()

In [303]:
x.grad

tensor(4.)

In [304]:
# option 1 - requires_grad_(False)
# option 2 - detach()
# option 3 - torch.no_grad()

In [305]:
x.requires_grad_(True)

tensor(2., requires_grad=True)

In [306]:
x

tensor(2., requires_grad=True)

In [307]:
y = x ** 2

In [308]:
y

tensor(4., grad_fn=<PowBackward0>)

In [309]:
y.backward()

In [310]:
x = torch.tensor([2.0], requires_grad=True)
x

tensor([2.], requires_grad=True)

In [311]:
z = x.detach().requires_grad_()


In [312]:
y = x ** 2

In [313]:
y

tensor([4.], grad_fn=<PowBackward0>)

In [314]:
y1 = z ** 2
y1

tensor([4.], grad_fn=<PowBackward0>)

In [315]:
y.backward()
y

tensor([4.], grad_fn=<PowBackward0>)

In [316]:
y1.backward()
print(z.grad)

tensor([4.])


In [317]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [318]:
y = x ** 2

In [319]:
y

tensor(4., grad_fn=<PowBackward0>)

In [320]:
y.backward()
y

tensor(4., grad_fn=<PowBackward0>)